CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    user_mail VARCHAR(254) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    user_role VARCHAR(50) NOT NULL,
    CONSTRAINT chk_users_role CHECK (user_role IN ('ADMIN', 'USUARIO_FINAL'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_user_mail_lower ON users (lower(user_mail));
